# Generated by Django 5.0.7 on 2024-08-27 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='category',
        ),
    ]
