# Generated by Django 5.0.7 on 2024-07-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(help_text='제품 ID', primary_key=True, serialize=False, unique=True),
        ),
    ]
